### ISSUE TITLE
Problem with date?

### ISSUE THREAD

**Issue by vianney78** [WallBB/focus-mybb-theme#1]
Hello since new mybb update, i've a problem with the date: i'll show you the screen of my problem
it don't show me the date only the hour, it's very problematic
![ttt](https://user-images.githubusercontent.com/33661575/32784973-9927fc76-c950-11e7-8d6d-4d55288b6966.PNG)
Your sincerely,
Vianney

**Comment by WallBB** [comment]
Hi Vianney,
I am in progress on updating the theme for MyBB 1.8.13 and it will be done by tomorrow.
Regards
WallBB

**Comment by vianney78** [comment]
Oh, okay nice, i love your theme :+1:

**Comment by WallBB** [comment]
Hi vianney78,
I will need your website url as well. 
Theme is updated but I have not found the date issue in previous version so I believe it might be some file is not updated or some plugin that might be affecting your site.

**Comment by WallBB** [comment]
Focus is updated to latest MyBB i.e. 1.8.13
 b6ae20b

Let me know, this should fix you issue.

Regards
WallBB

**Comment by vianney78** [comment]
Hi, my website address is: https://www.laconfreriedeselus.fr/forum/index.php

**Comment by vianney78** [comment]
It's not fix?

**Comment by WallBB** [comment]
Hi, I don't see this issue on your site, please check below screenshot
![screenshot-2017-11-17 forums la confrerie des elus](https://user-images.githubusercontent.com/18086627/32931621-1407cd4a-cb8b-11e7-8bca-e4d980d48dc6.png)

It might be related to user logged in view. 
Also I will need temporary login details to see the issue if it is present for logged in user.
Can you try changing your theme to default MyBB theme and let me know if the date doesn't show to you ?

**Comment by WallBB** [comment]
Can you verify this by selecting your global language to English, if date shows then it is issue with language translation pack.

**Comment by vianney78** [comment]
Okay it's a problem from the langage pack

**Comment by WallBB** [comment]
Okay, closing this issue now.
