### ISSUE TITLE
Font awesome icons missing on build #10

### ISSUE THREAD

**Issue by JustARandomGuyHere** [WallBB/focus-mybb-theme#3]
Hi,

I did a fresh install of mybb and tried to install focus build #10 from here -> https://community.mybb.com/mods.php?action=download&pid=671
![proof pic](https://vgy.me/z9xwWB.png)

the icons are missing. I tried build 9 and it works just fine.

Oh and I'm on debian 9, I noticed that you changed icons from example : "fa fa-bolt" to "fas fa-bolt". Maybe my system don't recognize the "fas" But I don't know what to do or update ?

**Comment by WallBB** [comment]
This will be fixed in version #11

Thanks for reporting :)

**Comment by WallBB** [comment]
Hey keketiger,
New theme will be updated this weekend, I will try to push this fix as soon as possible.

**Comment by WallBB** [comment]
This is fixed 96693d6
